objects/Roleplay_Campaign__c.object
<CustomObject>
    <description>Dreamforce 2017 by Mike Senn</description>
    <fields>
        <fullName>Notables__c</fullName>
        <label>Notables</label>
        <type>TextArea</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roleplay_Signup__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Roleplay_Campaign__c</referenceTo>
        <relationshipName>Signups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <formula>Roleplayer__r.Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <formula>Roleplayer__r.Level__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <formula>Roleplayer__r.Race__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Race</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roleplayer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Roleplayer</label>
        <referenceTo>Roleplayer__c</referenceTo>
        <relationshipName>Signups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Signup</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Roleplay Signup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roleplayer__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Experience__c</fullName>
        <label>Experience</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Noteables__c</fullName>
        <label>Noteables</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>TextArea</type>
    </fields>
    <label>Roleplayer</label>
    <nameField>
        <label>Roleplayer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roleplayers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampaignDetailExtension.cls
public class CampaignDetailExtension {

    private final Roleplay_Campaign__c campaign;

    public CampaignDetailExtension(ApexPages.StandardController stdController) {
        stdController.addFields(new List<String>{ 'id', 'notables__c' });
        this.campaign = (Roleplay_Campaign__c)stdController.getRecord();
    }
    
    public boolean getHasPlayerExperience() {
        return !getPlayerExperience().isEmpty();
    }
    
    
    public List<String> getListOfNotables() {
        return campaign.notables__c.split('\n');
    }

    public List<Roleplayer__c> getPlayers() {
        if (campaign == null) {
            return new List<Roleplayer__c>();
        }
        List<Roleplayer__c> players = new List<Roleplayer__c>();
        Id campaignId = campaign.Id;
		for(Roleplay_signup__c signup: [SELECT Id, Roleplayer__c
                                    FROM Roleplay_Signup__c WHERE Campaign__c = :campaignId]) {
			Id playerId = signup.roleplayer__c;
			players.add([SELECT Id, Name, skills__c, noteables__c, race__c, class__c, level__c FROM Roleplayer__c WHERE Id = :playerId]);
		}
        
        return players;
    }
    
    public List<Data> getPlayerExperience() {
        Id campaignId = campaign.Id;
		List<Data> data = new List<Data>();
        
        for (Roleplay_Signup__c signup : [SELECT Id, Roleplayer__r.Name, Roleplayer__r.Experience__c 
                                          FROM Roleplay_Signup__c WHERE Campaign__c = :campaignId]) {
            data.add(new Data(signup.Roleplayer__r.Name, signup.Roleplayer__r.Experience__c));
        }
        
        return data;
    }
    
    // Wrapper class for the chart
    public class Data {
        public String name {get; set;}
        public Integer experience {get; set;}
        public Data(String name, decimal experience) {
            this.name = name;
            this.experience = (integer) experience.round();
        }
    }

}