objects/Roleplay_Campaign__c.object
<CustomObject>
    <description>Dreamforce 2017 by Mike Senn</description>
    <fields>
        <fullName>Notables__c</fullName>
        <label>Notables</label>
        <type>TextArea</type>
    </fields>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Roleplay_Signup__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Roleplay_Campaign__c</referenceTo>
        <relationshipName>Signups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roleplayer_Name__c</fullName>
        <formula>Roleplayer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Roleplayer Name</label>
        <type>Text</type>
    </fields>
    <label>Signup</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Roleplay Signup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CampaignRegistrationComponentExtension.cls
public class CampaignRegistrationComponentExtension {
    
    public Roleplay_Campaign__c camp {get; set;}
    
    public Roleplay_Signup__c signup {get; set;}
    
    public CampaignRegistrationComponentExtension() {
        this.signup = new Roleplay_Signup__c();
    }
    
    public List<String> getListOfNotables() {
        return camp.notables__c.split('\n');
    }

    public List<String> getRegisteredRoleplayers() {
		Set<String> roleplayers = new Set<String>();
        for (Roleplay_Signup__c signup : [SELECT Roleplayer_Name__c 
                                          FROM Roleplay_Signup__c 
                                          WHERE Campaign__c = :camp.Id]) {
            roleplayers.add(signup.Roleplayer_Name__c);
        }
        return new List<String>(roleplayers);
    }

    public void save() {
        signup.campaign__c = camp.id;
        insert signup;
    }
}